name: test

on: push

jobs:   
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: truthy_db
          POSTGRES_USER: truthy_user
          POSTGRES_PASSWORD: truthy_password
        ports:
          - 5432:5432

      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.3.0

      - name: Set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
          DB_DATABASE_NAME: folio_db
          DB_USERNAME: folio_user
          DB_PASSWORD: folio_password

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run unit test
        run: npm run test:unit

      - name: Run e2e test
        run: npm run test:e2e